### PR TITLE
AvgInstaPower: change algo 

### PR DESCRIPTION
**Pull request by b3nj1**
Me again :)

Hi @inonoob ,

Where did the S4 AvgInstPower calculation come from? I noticed today that the S4 displayed power was quite different that what was shown over BLE. This PR attempts to match them closer. I couldn't find exactly what the S4 was doing.

The old algorithm is an average of a recent maximum power samples. This over estimates power from what I can tell because it drops the weaker strokes.

New algorithm is simply a rolling window average of the 6 samples. I had to change how samples were filtered because some strokes receive duplicate sample events, and I only want to count one. I came about the window size of 6 because that seemed pretty close to what the monitor showed - but not 100% exactly.

This PR also clears the power when the speed reaches 0 like the console does.

What do you think?

- Benjamin

### CODE REVIEW

**Comment by inonoob** [comment]
Hey,

Thanks for having a look into it. I was in contact with Sven the creator of the App Coxswain. And he told me how Waterrower tries to calculate the average of the instantaneous power. 
You can check his code here: [link](https://github.com/svenmeier/coxswain/blob/master/app/src/main/java/svenmeier/coxswain/rower/wired/PowerCalculator.java)

But It doesn't mean that it is correct ! If you méthode is better and closer to what the display shows then we should take yours. 

If you have seen the data from the power it change a lot. And a lot of the the power is just zero. 

But like I said, I take every improvement I can get to make it better !

Thanks for your contribution

**Comment by b3nj1** [comment]
Thanks for the link. I see Sven was looking for max power **within** a single stroke. I didn't see any occurrences of that in my very short testing, but I trust it happens. The previous code in some cases would look for max power across multiple strokes. So, neither my current PR or the previous code is quite right :) I'll fix it and update this PR when ready.

- Benjamin

**Comment by inonoob** [comment]
That was my e-mail with Sven:

"
Hi,

> The power. I don't know how you do it so that it doesn't drop to 0.

the values for power (Power 0x88) are unfortunately only supplied very inaccurately by the S4 monitor for each move.
The display in the S4 therefore forms an average of the last 5 strokes. I have recreated this in Coxswain.
"

So what do you think? What's closer to the s4 ?

**Comment by inonoob** [comment]
And I just saw the following: 

https://github.com/inonoob/pirowflo/blob/bc7dd6341eb9c07488176f1532bd624306585c05/src/wrtobleant.py#L115

        if event['type'] == 'avg_distance_cmps':
            if event['value'] == 0:
                self.WRValues.update({'instantaneous pace': 0})
                self.WRValues.update({'speed':0})
                self.avgInstaPowerStopped()

if we set those value to 0 if rower is at stop shouldn't also the stroke rate being set to 0 ?

**Comment by inonoob** [comment]
I also just understood that in the code we use two methods to set the Instantaneous value to zero: 

the first method is to check if the speed is 0 and then set those values to 0. 
the second is with the paddle turning and pulses. But the second method is faster as it don't have to wait for the other messages to come along before the speed value. The Pulse are send in a much higher frequency and it has it own method for it.

**Comment by b3nj1** [comment]
Ah - thanks for looking. I didn't notice the standstill detection in the pulse code when I was testing. I agree we shouldn't need both. I'll make sure that the pulse works as expected, and remove the speed-based rest. That should address the stroke_rate question since that is handled in the pulse-based/standstill code.

Since power uses a sample window, I think the standstill case should also clear the power sample list. This way we get a fresh reading when the paddles starts again.

Thanks!

**Comment by b3nj1** [comment]
I assume pulse is used for the HRM, right? I don't have one, but still the current method detects when the rower stops. So, I've reverted back to only using pulse() and not doing any speed-based checks.

I also added code to find the max-power within a single stroke which will be used for the 4-stroke average. I've changed back to 4 stoke instead of 6... it seems close to the monitor and keeps it consistent with the previous code.

After I resolve the conflict, please have a look. 

- Benjamin

**Comment by inonoob** [comment]
Hey no pulse are the amount of impulse seen in 25ms by the waterrower sensor. The grooved disk has teeth and the amount of counted grooves in 25ms give the amount of pulse. The bad thing here waterrower never tells you 0 pulse. It just stop broadcasting the pulse. So what I do is if the difference between 2 pulse messages is higher thab 300ms then I assume rower standstill. 

Check page 8 of this document https://github.com/svenmeier/coxswain/blob/master/doc/Water%20Rower%20S4%20S5%20USB%20Protocol%20Iss%201%2004.pdf

So it means you will update your update you project and re submit your pull request?

**Comment by b3nj1** [comment]
Oops - messed up the merge pretty badly. Let me fix that.

**Comment by b3nj1** [comment]
OK - I've fixed the merge. Please take a look.

**Comment by b3nj1** [comment]
Thanks for the pointer on pulse.

I've rebased my change on top of your latest reorganization, so if you like the enhancement, I believe it is ready to merge.

Thanks,
Benjamin

**Comment by inonoob** [comment]
Done

**Pull request merged**
