### PR TITLE
additional apt packages

### PR DESCRIPTION
**Pull request by b3nj1**
Hi,
Great project! It worked nicely with little effort. To help the next folks, I've added a couple of packages that I had to install in order for the install.sh to complete.

- Benjamin

### CODE REVIEW

**Comment by inonoob** [comment]
Hey, 

Thanks for the contribution. Can you explain where you got issues with the project. I tried it and others and they haven't report missing libraries. Have you a different setup ?

**Comment by inonoob** [comment]
I will try again to clone on a fresh installed raspbian to double check the issue. I though we had all it fixed with python3-gi-cairo

**Comment by b3nj1** [comment]
The pip install step of install.sh failed for me, and the failure messages suggested these packages. After, all worked well. 

I’m on an raspberry pi 3B running:
Linux rpio 5.4.83-v7+ #1379 SMP Mon Dec 14 13:08:57 GMT 2020 armv7l GNU/Linux

**Comment by inonoob** [comment]
Hey @b3nj1 many thanks for the feedback will merge it in 2 hours when the kids are in bed :)

**Comment by inonoob** [comment]
hey, 

I tried on a fresh Pi zero W and I haven't got any trouble. Might a be an issue for Pi's with more cores ? From Pi3 and up ?  

 ``` 
----------------------------------------------
install needed python3 modules for the project        
----------------------------------------------
 

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyserial (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/07/bc/587a445451b253b285629263eb51c2d8e9bcea4fc97826266d186f96f558/pyserial-3.5-py2.py3-none-any.whl (90kB)
    100% |████████████████████████████████| 92kB 330kB/s 
Requirement already satisfied: PyGObject in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (3.30.4)
Collecting dbus-python (from -r requirements.txt (line 3))
  Downloading https://www.piwheels.org/simple/dbus-python/dbus_python-1.2.16-cp37-cp37m-linux_armv6l.whl (386kB)
    100% |████████████████████████████████| 389kB 152kB/s 
Collecting numpy (from -r requirements.txt (line 4))
  Downloading https://www.piwheels.org/simple/numpy/numpy-1.20.1-cp37-cp37m-linux_armv6l.whl (11.6MB)
    100% |████████████████████████████████| 11.6MB 6.6kB/s 
Collecting pyusb (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/b5/28/b857ac783257f142932b23379d761a3d9becf6deecf5d14075ec19bdb890/pyusb-1.1.1-py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 416kB/s 
Collecting gatt (from -r requirements.txt (line 6))
  Downloading https://www.piwheels.org/simple/gatt/gatt-0.2.7-py3-none-any.whl
Collecting supervisor (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/08/b2/6f9f199774860e3c180dcdf9bf3191a8588f5ece417d03661d25155cfdfe/supervisor-4.2.1-py2.py3-none-any.whl (738kB)
    100% |████████████████████████████████| 747kB 97kB/s 
Requirement already satisfied: pycairo>=1.11.1 in /usr/lib/python3/dist-packages (from PyGObject->-r requirements.txt (line 2)) (1.16.2)
Installing collected packages: pyserial, dbus-python, numpy, pyusb, gatt, supervisor
Successfully installed dbus-python-1.2.16 gatt-0.2.7 numpy-1.20.1 pyserial-3.5 pyusb-1.1.1 supervisor-4.2.1
```

**Comment by b3nj1** [comment]
My 3B installation hasn't been "fresh" for several years. It has been kept up-to-date with update/upgrade, but it shouldn't be considered typical in any way. So, feel free to close this PR instead of merging it.

- Benjamin

**Comment by inonoob** [comment]
If you had trouble, let's include it :) so we can be sure that others don't have the same issue.

**Pull request merged**
