### PR TITLE
deepcopy for WRValue* and its copies

### PR DESCRIPTION
**Pull request by b3nj1**
@inonoob & @sjeri , here is my change which makes the WRValue* copies. Feel free to drop the PR if @sjeri's fix is preferred.

Thanks,
Benjamin

### CODE REVIEW

**Comment by inonoob** [comment]
Since the merge, I have the following trouble: 

```
2021-02-21 20:35:25,944 - dbus.connection - ERROR - Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gatt/gatt_linux.py", line 539, in properties_changed
    self.service.device.characteristic_value_updated(characteristic=self, value=bytes(value))
  File "/home/pi/pirowflo/src/smartrowreader.py", line 76, in characteristic_value_updated
    self.notify_callbacks(self.buffer)
  File "/home/pi/pirowflo/src/smartrowreader.py", line 92, in notify_callbacks
    cb(event)
  File "/home/pi/pirowflo/src/smartrowtobleant.py", line 103, in on_row_event
    self.elapsedtime()
  File "/home/pi/pirowflo/src/smartrowtobleant.py", line 65, in elapsedtime
    elaspedtimecalc = int(time.time() - self.starttime)
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```

**Comment by inonoob** [comment]
Hey,

since the merger, I'm fighting the following probleme: 

```
starting heart beat
{'stroke_rate': 0, 'total_strokes': 0, 'total_distance_m': 0, 'instantaneous pace': 0, 'speed': 0, 'watts': 0, 'total_kcal': 0, 'total_kcal_hour': 0, 'total_kcal_min': 0, 'heart_rate': 0, 'elapsedtime': 0.0, 'work': 0, 'stroke_length': 0, 'force': 0, 'watts_avg': 0, 'pace_avg': 0}
{'stroke_rate': 0, 'total_strokes': 0, 'total_distance_m': 0, 'instantaneous pace': 0, 'speed': 0, 'watts': 0, 'total_kcal': 0, 'total_kcal_hour': 0, 'total_kcal_min': 0, 'heart_rate': 0, 'elapsedtime': 0.0, 'work': 0, 'stroke_length': 0, 'force': 0, 'watts_avg': 0, 'pace_avg': 0}
2021-02-21 20:37:55,773 - dbus.connection - ERROR - Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gatt/gatt_linux.py", line 539, in properties_changed
    self.service.device.characteristic_value_updated(characteristic=self, value=bytes(value))
  File "/home/pi/pirowflo/src/smartrowreader.py", line 76, in characteristic_value_updated
    self.notify_callbacks(self.buffer)
  File "/home/pi/pirowflo/src/smartrowreader.py", line 92, in notify_callbacks
    cb(event)
  File "/home/pi/pirowflo/src/smartrowtobleant.py", line 75, in on_row_event
    self.elapsedtime()
  File "/home/pi/pirowflo/src/smartrowtobleant.py", line 65, in elapsedtime
    elaspedtimecalc = int(time.time() - self.starttime)
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
2021-02-21 20:37:55,873 - dbus.connection - ERROR - Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gatt/gatt_linux.py", line 539, in properties_changed
    self.service.device.characteristic_value_updated(characteristic=self, value=bytes(value))
  File "/home/pi/pirowflo/src/smartrowreader.py", line 76, in characteristic_value_updated
    self.notify_callbacks(self.buffer)
  File "/home/pi/pirowflo/src/smartrowreader.py", line 92, in notify_callbacks
    cb(event)
  File "/home/pi/pirowflo/src/smartrowtobleant.py", line 83, in on_row_event
    self.elapsedtime()
  File "/home/pi/pirowflo/src/smartrowtobleant.py", line 65, in elapsedtime
    elaspedtimecalc = int(time.time() - self.starttime)
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
2021-02-21 20:37:55,972 - dbus.connection - ERROR - Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gatt/gatt_linux.py", line 539, in properties_changed
    self.service.device.characteristic_value_updated(characteristic=self, value=bytes(value))
  File "/home/pi/pirowflo/src/smartrowreader.py", line 76, in characteristic_value_updated
    self.notify_callbacks(self.buffer)
  File "/home/pi/pirowflo/src/smartrowreader.py", line 92, in notify_callbacks
    cb(event)
  File "/home/pi/pirowflo/src/smartrowtobleant.py", line 93, in on_row_event
    self.elapsedtime()
  File "/home/pi/pirowflo/src/smartrowtobleant.py", line 65, in elapsedtime
    elaspedtimecalc = int(time.time() - self.starttime)
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
2021-02-21 20:37:56,073 - dbus.connection - ERROR - Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gatt/gatt_linux.py", line 539, in properties_changed
    self.service.device.characteristic_value_updated(characteristic=self, value=bytes(value))
  File "/home/pi/pirowflo/src/smartrowreader.py", line 76, in characteristic_value_updated
    self.notify_callbacks(self.buffer)
  File "/home/pi/pirowflo/src/smartrowreader.py", line 92, in notify_callbacks
    cb(event)
  File "/home/pi/pirowflo/src/smartrowtobleant.py", line 103, in on_row_event
    self.elapsedtime()
  File "/home/pi/pirowflo/src/smartrowtobleant.py", line 65, in elapsedtime
    elaspedtimecalc = int(time.time() - self.starttime)
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
2021-02-21 20:37:56,173 - dbus.connection - ERROR - Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gatt/gatt_linux.py", line 539, in properties_changed
    self.service.device.characteristic_value_updated(characteristic=self, value=bytes(value))
  File "/home/pi/pirowflo/src/smartrowreader.py", line 76, in characteristic_value_updated
    self.notify_callbacks(self.buffer)
  File "/home/pi/pirowflo/src/smartrowreader.py", line 92, in notify_callbacks
    cb(event)
  File "/home/pi/pirowflo/src/smartrowtobleant.py", line 120, in on_row_event
    self.elapsedtime()
  File "/home/pi/pirowflo/src/smartrowtobleant.py", line 65, in elapsedtime
    elaspedtimecalc = int(time.time() - self.starttime)
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
2021-02-21 20:37:56,275 - dbus.connection - ERROR - Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gatt/gatt_linux.py", line 539, in properties_changed
    self.service.device.characteristic_value_updated(characteristic=self, value=bytes(value))
  File "/home/pi/pirowflo/src/smartrowreader.py", line 76, in characteristic_value_updated
    self.notify_callbacks(self.buffer)
  File "/home/pi/pirowflo/src/smartrowreader.py", line 92, in notify_callbacks
    cb(event)
  File "/home/pi/pirowflo/src/smartrowtobleant.py", line 136, in on_row_event
    self.elapsedtime()
  File "/home/pi/pirowflo/src/smartrowtobleant.py", line 65, in elapsedtime
    elaspedtimecalc = int(time.time() - self.starttime)
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```

**Comment by inonoob** [comment]
Is the code now so efficient that error which were covered by the slowness of the code now shows up ?

**Comment by sjeri** [comment]
I'm not sure why it did not show up before but the starttime seems to be initialized in the force message only and in this case another message type is first. Faced similar before and added more settings for other messages.

**Comment by inonoob** [comment]
I might have found how to fix it. 
I init the self.starttime = None. if I changed it to self.starttime = time.time() it work

**Comment by b3nj1** [comment]
I have an S4 monitor, so I couldn't test that :(

With your change to set it during init, is it possible that the starttime will be set before you start rowing?

Do you know what order the SR messages come in? The starttime variable isn't initialized until FORCE_MESSAGE. Is that guaranteed to be first? If not, maybe the initialization of it should be moved to the start of on_row_event(). 

I noticed that I hid the creation member variables inside _reset_state(). That's not good practice, so I'll send a PR for that.

- Benjamin

**Comment by inonoob** [comment]
I might have found the issue. 

ok the Smartrow keeps the last value in memory. If you Start the connection with the SmartRow you will get the feedback that the rower is at standstill but the distance is not 0. 

https://github.com/inonoob/pirowflo/blob/364c816f88e02d101e50d762b3892cd601b7683a/src/smartrowtobleant.py#L64
        elif self.fullstop == True and self.WRValues.get('total_distance_m') !=0: 

this line is triggered. 

This is used to check if we are in the middle of an HIIT training. So the Rower is doing a full stop but will start to row in the same workout. 

The Rowing reset is too slow. So the event call back start right at the beginning with the old data from the last workout. First the heartbeat must start and then only the reset is triggered. And in that exact timeframe the event are send : rower at full stop: ! but distance not 0. 

Now how to fix that ?

**Comment by inonoob** [comment]
Might it be an idea to introduce a check self.initial_reset = False. And only after the Reset to set it to True and use it as additional check ?

**Comment by sjeri** [comment]
Hmm, I did not think of the HIIT scenario and added an initialisation to each event in case the time is not set yet... Maybe not a good idea... However this should be solved, I'll adopt. But will look into this as well tomorrow.

**Comment by inonoob** [comment]
You won't believe it. It has to do with timing.  If you pull the smartrow to active it and then during that time putting it back to wait the reset is so fast that you will end up with 1m already after the reset. It is super sensitive.

**Comment by sjeri** [comment]
so what about this...
```
elif self.fullstop == True and self.WRValues.get('total_distance_m') !=0:
            elaspedtimecalc = int(time.time() - self.starttime)
            self.WRValues.update({'elapsedtime':elaspedtimecalc})
``` 

adding 
``` 
if not self.starttime:
                    self.starttime = time.time()
``` 
there?

**Comment by inonoob** [comment]
The SmartRow is even so sensitiv if you only touch that handle after a reset, the system will see 1m !

**Comment by inonoob** [comment]
That solve the issue with the error but not the main issue. 
@sjeri how to you active the Smartrow and then start pirrowflo. I suppose you pull the handle, start the script and put the handle back ? Then you already will have 1m and the counter starts. 
The thing is I only know from the App coxswain that it also initiate a reset. Which means, it an third party app don't do the reset again of the SmartRow and you have touched the handle, the time counter already has started even if you don't really has started the workout.

**Comment by sjeri** [comment]
In my scenario it is a service. As soon as a HR device is detected, the smartrow thread is started. I then pull the handle and start rowing. But as said I have set the time there in case it is not set. So yes. In this case the time starts with activation of the smartrow... and may loose accuracy. So some additional reset may be required as you said... Too late already to think of ;)

**Comment by inonoob** [comment]
I would say we may have two solution. 

1. Introduce a sleep after the heartbeat and the first reset to let user put the handle back to get ready to start 

```
    sleep(1)
    reset(smartrow)
    sleep(1)
    SRtoBLEANT.Initial_reset = True
```
this gives the user 1 sec to put the handle back 

2. or we say for the first stroke after a fresh reset, it only start if 3m to 4m has been passed which result in an error for 0.5s or error

**Comment by inonoob** [comment]
I went with the additional sleep and your fix.

**Comment by inonoob** [comment]
@sjeri have you seen the screen update ?

**Comment by sjeri** [comment]
Yes, just had a quick look but will look closer in the morning. My version is still in progress... Got myself a bit too much into detail when I wanted scrollable options and submenus^^
But it works and I'll have to add content next.

**Comment by inonoob** [comment]
Oh I will be please to see your. But like I said. I really think if we could make the HRM stuff as an option as well to choose if active from screen or if HRM is found we would change to your code. As I think you have a bit more experience in Python.

**Comment by sjeri** [comment]
Let's see^^ I'm just used to due to work. I'm very sure there are many more advanced coders who'd hate my coding ;)
I'll have to merge your changes tomorrow and will push what I have then. Maybe we can learn from each other on that.

**Comment by sjeri** [comment]
I like your idea of the screen being an own service.  Not sure how to show the rowing data then. But maybe this is not so important

**Comment by inonoob** [comment]
thanks. I though it might be best so user can then choose to have it or not. And I can use the Supervisor to check if pirowflo has started or failed. It would be in sync with the webserver. 
I'm still missing a screensaver as the OLED tend to "burn in the picture"

**Pull request merged**
